<?php
namespace Theob\ReportGenerator;

class Installer
{
    /**
     * Run after package installation
     */
    public static function postInstall()
    {
        self::debugPaths(); // DEBUG: Tambahkan ini untuk troubleshooting
        self::setupConfig();
        self::createDirectories();
        self::showWelcomeMessage();
    }

    /**
     * Run after package update
     */
    public static function postUpdate()
    {
        self::setupConfig();
        self::createDirectories();
    }

    /**
     * Create configuration file in user's project
     */
    private static function setupConfig()
    {
        $projectRoot = self::getProjectRoot();
        $configFile = $projectRoot . '/config/reportGenerator.config.php';
        
        echo "🔍 Project Root: " . $projectRoot . "\n";
        echo "📁 Config Path: " . $configFile . "\n";
        
        // Create config directory if not exists
        $configDir = dirname($configFile);
        if (!is_dir($configDir)) {
            if (mkdir($configDir, 0755, true)) {
                echo "✅ Created config directory: " . $configDir . "\n";
            } else {
                echo "❌ Failed to create config directory: " . $configDir . "\n";
                return;
            }
        }
        
        // Only create config if it doesn't exist
        if (!file_exists($configFile)) {
            $configContent = self::getConfigTemplate();
            if (file_put_contents($configFile, $configContent) !== false) {
                echo "✅ Created config file: " . $configFile . "\n";
            } else {
                echo "❌ Failed to create config file: " . $configFile . "\n";
            }
        } else {
            echo "ℹ️ Config file already exists: " . $configFile . "\n";
        }
    }

    /**
     * Create necessary directories in user's project
     */
    private static function createDirectories()
    {
        $projectRoot = self::getProjectRoot();
        $directories = [
            '/exports/excel',
            '/exports/pdf',
            '/exports/csv',
            '/exports/html',
            '/storage/reports/temp'
        ];

        foreach ($directories as $dir) {
            $fullPath = $projectRoot . $dir;
            if (!is_dir($fullPath)) {
                if (mkdir($fullPath, 0755, true)) {
                    echo "✅ Created directory: " . $fullPath . "\n";
                    
                    // Create .gitignore for temp directory
                    if (strpos($dir, 'temp') !== false) {
                        file_put_contents($fullPath . '/.gitignore', "*\n!.gitignore");
                    }
                } else {
                    echo "❌ Failed to create directory: " . $fullPath . "\n";
                }
            } else {
                echo "ℹ️ Directory already exists: " . $fullPath . "\n";
            }
        }
    }

    /**
     * Get the project root path - METHOD YANG DIPERBAIKI
     */
    private static function getProjectRoot(): string
    {
        // Strategy 1: Dari vendor path (PALING RELIABLE)
        // Dari: vendor/theob/report-generator/src/Installer.php
        $vendorPath = dirname(__DIR__, 2); // vendor/theob/report-generator
        $possibleRoot = dirname($vendorPath); // project-root
        
        if (file_exists($possibleRoot . '/composer.json') || 
            file_exists($possibleRoot . '/vendor/autoload.php')) {
            return realpath($possibleRoot);
        }
        
        // Strategy 2: Current working directory
        $cwd = getcwd();
        if (file_exists($cwd . '/composer.json') || 
            file_exists($cwd . '/vendor/autoload.php')) {
            return realpath($cwd);
        }
        
        // Strategy 3: Naik terus sampai ketemu composer.json
        $current = $cwd;
        $previous = '';
        while ($current !== $previous) {
            if (file_exists($current . '/composer.json') || 
                file_exists($current . '/vendor/autoload.php')) {
                return realpath($current);
            }
            $previous = $current;
            $current = dirname($current);
        }
        
        echo "⚠️  Could not find project root, using fallback: " . $cwd . "\n";
        return realpath($cwd); // Fallback
    }

    /**
     * Configuration template - DIPERBAIKI
     */
    private static function getConfigTemplate(): string
    {
        return <<<'EOT'
<?php
/**
 * Report Generator Configuration
 * 
 * This file is automatically generated. Edit with your actual database credentials.
 */

return [
    'database' => [
        'host' => 'localhost',
        'dbname' => 'your_database_name',
        'username' => 'your_username',
        'password' => 'your_password',
        'port' => 3306,
        'charset' => 'utf8mb4'
    ],
    'export' => [
        'excel' => [
            'creator' => 'Report Generator',
            'title' => 'Generated Report'
        ],
        'pdf' => [
            'paper_size' => 'A4',
            'orientation' => 'portrait'
        ],
        'default_format' => 'html'
    ],
    'paths' => [
        'exports' => 'exports/',
        'templates' => 'templates/'
    ]
];
EOT;
    }

    /**
     * Show welcome message
     */
    private static function showWelcomeMessage()
    {
        $projectRoot = self::getProjectRoot();
        
        echo "\n" . str_repeat("=", 60) . "\n";
        echo "🎉 REPORT GENERATOR INSTALLED SUCCESSFULLY!\n";
        echo str_repeat("=", 60) . "\n";
        echo "Project Root: " . $projectRoot . "\n\n";
        echo "Next steps:\n\n";
        echo "1. Edit your database configuration:\n";
        echo "   📁 config/reportGenerator.config.php\n\n";
        echo "2. Use in your code:\n";
        echo "   <?php\n";
        echo "   require 'vendor/autoload.php';\n";
        echo "   use Theob\\ReportGenerator\\ReportGenerator;\n";
        echo "   \$report = new ReportGenerator();\n\n";
        echo "3. Your export files will be saved in:\n";
        echo "   📁 exports/excel/, exports/pdf/, etc.\n";
        echo str_repeat("=", 60) . "\n\n";
    }

    /**
     * DEBUG: Method untuk troubleshooting path
     */
    private static function debugPaths()
    {
        echo "\n🔍 DEBUG PATH INFORMATION:\n";
        echo "Current File: " . __FILE__ . "\n";
        echo "__DIR__: " . __DIR__ . "\n";
        echo "dirname(__DIR__): " . dirname(__DIR__) . "\n";
        echo "dirname(__DIR__, 2): " . dirname(__DIR__, 2) . "\n";
        echo "dirname(__DIR__, 3): " . dirname(__DIR__, 3) . "\n";
        echo "getcwd(): " . getcwd() . "\n";
        
        // Cek vendor path
        $vendorPath = dirname(__DIR__, 2);
        echo "Vendor Path: " . $vendorPath . "\n";
        echo "Vendor exists: " . (is_dir($vendorPath) ? 'YES' : 'NO') . "\n";
        
        $projectRoot = dirname($vendorPath);
        echo "Project Root (calculated): " . $projectRoot . "\n";
        echo "Project Root exists: " . (is_dir($projectRoot) ? 'YES' : 'NO') . "\n";
        
        // Cek indicators
        $indicators = [
            $projectRoot . '/composer.json',
            $projectRoot . '/vendor/autoload.php',
            getcwd() . '/composer.json'
        ];
        
        foreach ($indicators as $indicator) {
            echo "Indicator {$indicator}: " . (file_exists($indicator) ? 'EXISTS' : 'NOT EXISTS') . "\n";
        }
        echo "---\n";
    }
}