<?php
namespace Theob\ReportGenerator;

class Installer
{
    /**
     * Run after package installation
     */
    public static function postInstall()
    {
        self::setupConfig();
        self::createDirectories();
        self::showWelcomeMessage();
    }

    /**
     * Run after package update
     */
    public static function postUpdate()
    {
        self::setupConfig();
        self::createDirectories();
    }

    /**
     * Create configuration file in user's project
     */
    private static function setupConfig()
    {
        $projectRoot = self::getProjectRoot();
        $configFile = $projectRoot . '/config/reportGenerator.config.php';
        
        // Create config directory if not exists
        $configDir = dirname($configFile);
        if (!is_dir($configDir)) {
            mkdir($configDir, 0755, true);
        }
        
        // Only create config if it doesn't exist
        if (!file_exists($configFile)) {
            $configContent = self::getConfigTemplate();
            if (file_put_contents($configFile, $configContent) !== false) {
                echo "✅ Created config file: " . $configFile . "\n";
            } else {
                echo "⚠️  Failed to create config file: " . $configFile . "\n";
            }
        } else {
            echo "ℹ️  Config file already exists: " . $configFile . "\n";
        }
    }

    /**
     * Create necessary directories in user's project
     */
    private static function createDirectories()
    {
        $projectRoot = self::getProjectRoot();
        $directories = [
            '/exports/excel',
            '/exports/pdf',
            '/exports/csv',
            '/exports/html',
            '/storage/reports/temp'
        ];

        foreach ($directories as $dir) {
            $fullPath = $projectRoot . $dir;
            if (!is_dir($fullPath)) {
                if (mkdir($fullPath, 0755, true)) {
                    echo "✅ Created directory: " . $fullPath . "\n";
                    
                    // Create .gitignore for temp directory
                    if (strpos($dir, 'temp') !== false) {
                        file_put_contents($fullPath . '/.gitignore', "*\n!.gitignore");
                    }
                } else {
                    echo "⚠️  Failed to create directory: " . $fullPath . "\n";
                }
            }
        }
    }

    /**
     * Get the project root path (where user's composer.json is located)
     */
    private static function getProjectRoot(): string
    {
        // Method 1: Current working directory (usually the project root)
        $cwd = getcwd();
        if (file_exists($cwd . '/composer.json')) {
            return realpath($cwd);
        }
        
        // Method 2: Go up from vendor directory
        $vendorPath = dirname(__DIR__, 3);
        if (file_exists($vendorPath . '/composer.json')) {
            return realpath($vendorPath);
        }
        
        return $cwd; // Fallback
    }

    /**
     * Configuration template
     */
    private static function getConfigTemplate(): string
    {
        return <<<'EOT'
<?php
/**
 * Report Generator Configuration
 * 
 * This file is automatically generated. Edit with your actual database credentials.
 */

return [
    'database' => [
        'host' => 'localhost',
        'dbname' => 'your_database_name',
        'username' => 'your_username',
        'password' => 'your_password',
        'port' => 3306,
        'charset' => 'utf8mb4'
    ],
    'export' => [
        'excel' => [
            'creator' => 'Report Generator',
            'title' => 'Generated Report'
        ],
        'pdf' => [
            'paper_size' => 'A4',
            'orientation' => 'portrait'
        ],
        'default_format' => 'html'
    ],
    'paths' => [
        'exports' => 'exports/',
        'templates' => 'templates/'
    ]
];
EOT;
    }

    /**
     * Show welcome message
     */
    private static function showWelcomeMessage()
    {
        echo "\n" . str_repeat("=", 60) . "\n";
        echo "🎉 REPORT GENERATOR INSTALLED SUCCESSFULLY!\n";
        echo str_repeat("=", 60) . "\n";
        echo "Next steps:\n\n";
        echo "1. Edit your database configuration:\n";
        echo "   📁 config/reportGenerator.config.php\n\n";
        echo "2. Use in your code:\n";
        echo "   <?php\n";
        echo "   require 'vendor/autoload.php';\n";
        echo "   use Theob\\ReportGenerator\\ReportGenerator;\n";
        echo "   \$report = new ReportGenerator();\n\n";
        echo "3. Your export files will be saved in:\n";
        echo "   📁 exports/excel/, exports/pdf/, etc.\n";
        echo str_repeat("=", 60) . "\n\n";
    }
}